=== Rodez-IUT/dut-info2-filmprovider-RomainFaure12/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!ENTITY copyrightLib "&#xA9;Librairie  Internet 2020">
<!ENTITY % personnel "(nom,prenom?)">
<!ELEMENT librairie (en-tête+,livre+)>

<!ELEMENT en-tête (text)>

<!ELEMENT img EMPTY>
<!ATTLIST img source CDATA #REQUIRED
              title CDATA #IMPLIED
>
<!ELEMENT em (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT text (#PCDATA|strong|em|img)*>

<!ELEMENT titre (#PCDATA)>
<!ELEMENT description (#PCDATA|strong|em|img)* >
<!ELEMENT prix (#PCDATA)>
<!ATTLIST prix devise (euro|livre|dollar) "euro">
<!ATTLIST prix type (HT|TTC) "HT">
<!ATTLIST prix tva CDATA #FIXED "5.5">
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT direction (%personnel;)>
<!ELEMENT membres (#PCDATA)>
<!ELEMENT collectif (direction,membres)>
<!ELEMENT auteurs ((nom,prenom?)+)>
<!ELEMENT livre (titre,(auteurs+|collectif),description,prix)>
<!ATTLIST livre ISBN ID #REQUIRED>

=== Rodez-IUT/dut-info2-filmprovider-RomainFaure12/Part1-XML-DTD/resources/XML3/Librairie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">
<librairie>
    <en-tête>
        <text>c'est <em>une</em> <strong>Librairie</strong><img source="img.png"/>&copyrightLib;</text>
    </en-tête>
    <livre ISBN="id_22">
        <titre></titre>
        <auteurs>
            <nom>BONJOUR</nom>
        </auteurs>
        <description></description>
        <prix tva="5.5" devise="euro" type="HT">42</prix>
    </livre>
    <livre ISBN="id_42">
        <titre></titre>
        <collectif>
            <direction>
                <nom>salut</nom>
            </direction>
            <membres></membres>
        </collectif>
        <description>je suis nul</description>
        <prix type="HT" devise="euro" tva="5.5">85</prix>
    </livre>
</librairie>
